# Generated by Django 2.1.2 on 2018-12-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='创建人', to=settings.AUTH_USER_MODEL),
        ),
    ]
