# Generated by Django 2.1.2 on 2019-01-08 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190108_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producter', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
