# Generated by Django 2.1.2 on 2019-01-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190108_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_time'], 'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
        migrations.AlterField(
            model_name='product',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
