# Generated by Django 2.1.2 on 2019-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190115_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.IntegerField(default=-1, verbose_name='产品级别'),
        ),
    ]
