# Generated by Django 2.1.2 on 2019-01-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-level'], 'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
    ]
