# Generated by Django 2.1.2 on 2019-01-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcase',
            name='apiurl',
            field=models.CharField(default='www.baidu.com', max_length=200, verbose_name='url地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcase',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
