# Generated by Django 2.1.2 on 2019-01-21 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_auto_20190121_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcase',
            name='webtester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='测试负责人'),
        ),
    ]
