# Generated by Django 2.1.2 on 2019-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0003_auto_20190121_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcasestep',
            old_name='Webcase',
            new_name='webcase',
        ),
        migrations.RemoveField(
            model_name='webcasestep',
            name='webassertdata',
        ),
        migrations.RemoveField(
            model_name='webcasestep',
            name='webfindmethod',
        ),
        migrations.RemoveField(
            model_name='webcasestep',
            name='webtestdata',
        ),
        migrations.RemoveField(
            model_name='webcasestep',
            name='webteststep',
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webevelement',
            field=models.CharField(max_length=800, verbose_name='CSS选择器'),
        ),
    ]
