# Generated by Django 2.1.2 on 2018-12-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='apiurl',
            field=models.CharField(max_length=200, null=True, verbose_name='url地址'),
        ),
    ]
