# Generated by Django 2.1.2 on 2018-12-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_apiinfo_apiurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
