# Generated by Django 2.1.2 on 2018-12-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20181227_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
