# Generated by Django 2.1.2 on 2018-12-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20181227_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='apiresponse',
            field=models.CharField(max_length=5000, null=True, verbose_name='响应数据json'),
        ),
    ]
