# Generated by Django 2.1.2 on 2019-01-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20181227_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apis',
            options={'ordering': ['-create_time'], 'verbose_name': 'API测试用例', 'verbose_name_plural': 'API测试用例'},
        ),
    ]
