# Generated by Django 2.1.2 on 2019-01-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20190108_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apitester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='测试负责人'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
