# Generated by Django 2.1.2 on 2019-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_auto_20190108_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='apijson',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='请求数据json'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='apiparamvalue',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='请求参数param'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='apiresponse',
            field=models.TextField(max_length=5000, null=True, verbose_name='响应数据json'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='apistatus',
            field=models.BooleanField(default=True, verbose_name='是否通过'),
        ),
    ]
