# Generated by Django 2.1.2 on 2019-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0012_auto_20190108_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='bodytype',
            field=models.CharField(choices=[('json', 'json'), ('form', 'form')], default='json', max_length=200, null=True, verbose_name='body类型'),
        ),
    ]
