# Generated by Django 2.1.2 on 2019-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0013_apiinfo_bodytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='apistatus',
            field=models.BooleanField(default=True, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='bodytype',
            field=models.CharField(choices=[('application/json;charset=utf-8', 'application/json;charset=utf-8'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded')], default='json', max_length=200, null=True, verbose_name='body类型'),
        ),
    ]
