# Generated by Django 2.1.2 on 2019-01-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0014_auto_20190109_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='apijson',
            field=models.TextField(default=None, max_length=800, null=True, verbose_name='请求数据json'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='apiparamvalue',
            field=models.TextField(default=None, max_length=800, null=True, verbose_name='请求参数param'),
        ),
    ]
