# Generated by Django 2.1.2 on 2019-01-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0016_auto_20190109_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='apijson',
            field=models.TextField(blank='None', max_length=800, null=True, verbose_name='请求数据json'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='apiparamvalue',
            field=models.TextField(blank='None', max_length=800, null=True, verbose_name='请求参数param'),
        ),
    ]
