# Generated by Django 2.1.2 on 2019-01-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0022_auto_20190117_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apiname',
            field=models.CharField(help_text='请输入后端模块', max_length=100, verbose_name='后端模块'),
        ),
    ]
