# Generated by Django 2.1.2 on 2019-01-04 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_testrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'ordering': ['-login_time'], 'verbose_name': '登陆计数', 'verbose_name_plural': '登陆计数'},
        ),
        migrations.AlterModelOptions(
            name='testrecord',
            options={'ordering': ['-test_time'], 'verbose_name': '测试计数', 'verbose_name_plural': '测试计数'},
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
